import os
import json
import logging
from pathlib import Path
from typing import Dict, Any, List

# Try to import OpenAI for direct LLM calls (Token savings)
try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

logger = logging.getLogger("ReportGenerator")

class ReportGenerator:
    """
    Generates a deterministic Markdown report by aggregating artifacts
    and using an LLM to write the narrative sections.
    """
    
    @staticmethod
    def generate(run_id: str, research_goal: str) -> str:
        """
        Compiles experiments/{run_id} into FINAL_REPORT.md
        """
        logger.info(f"Generating Final Report for Run {run_id}...")
        
        # 1. Setup Paths
        base_dir = Path(__file__).parent.parent / "experiments" / run_id
        report_path = base_dir / "FINAL_REPORT.md"
        
        if not base_dir.exists():
            return f"Error: Run directory {base_dir} does not exist."

        # 2. Load Artifacts
        dataset_meta = ReportGenerator._load_json(base_dir / "dataset_used.json")
        raw_results = ReportGenerator._load_json(base_dir / "raw_results.json")
        
        # Determine Dataset Info (Handle Procedural vs Loaded)
        ds_source = "Unknown"
        ds_type = "Unknown"
        ds_details = "{}"
        
        if dataset_meta.get("data_modality") == "procedural":
            ds_source = "Procedural Generation (Synthetic)"
            ds_type = "Synthetic Regression/Classification"
            ds_details = json.dumps(dataset_meta, indent=2)
        else:
            ds_source = dataset_meta.get('dataset_id') or dataset_meta.get('source_family', 'Unknown')
            ds_type = dataset_meta.get('type') or dataset_meta.get('requirements', {}).get('task_type', 'Unknown')
            ds_details = json.dumps(dataset_meta.get('parameters', {}), indent=2)

        # 3. Visualizations
        plots = list(base_dir.glob("*.png"))
        plot_markdown = ""
        if plots:
            plot_markdown = "## 3.1 Visualizations\n\n"
            for p in plots:
                # Use relative path for Markdown
                rel_path = p.name
                plot_markdown += f"![{p.stem}]({rel_path})\n*Figure: {p.stem}*\n\n"
        
        # 4. Generate Narrative (LLM)
        narrative = ReportGenerator._generate_narrative(research_goal, dataset_meta, raw_results)
        
        # 5. Assemble Report (Deterministic Layout)
        report_content = f"""# Final Research Report
**Run ID:** `{run_id}`
**Date:** {os.getenv("DATE", "N/A")}

---

## 1. Executive Summary
{narrative.get('executive_summary', 'Summary not available.')}

## 2. Methodology
**Research Goal:** {research_goal}

### Dataset
- **Source:** {ds_source}
- **Type:** {ds_type}
- **Details:** 
```json
{ds_details}
```

{narrative.get('methodology_description', '')}

## 3. Results & Discussion
{narrative.get('results_discussion', 'See raw results below.')}

{plot_markdown}
### Quantitative Metrics
- **Raw Results:** [raw_results.json](raw_results.json)
- **Dataset Metadata:** [dataset_used.json](dataset_used.json)

## 4. Audit Trail
- **Code:** [run_experiment.py](run_experiment.py)
- **Logs:** [execution.log](execution.log)


---
*Generated by Epsilon Autonomous Research Engine*
"""
        
        # 6. Save
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_content)
            
        logger.info(f"Report saved to {report_path}")
        
        # 7. Generate Standalone HTML
        try:
            html_path = ReportGenerator._generate_html(run_id, report_content, base_dir)
            logger.info(f"HTML Report saved to {html_path}")
        except Exception as e:
            logger.error(f"Failed to generate HTML report: {e}")
            html_path = None

        return str(report_path)

    @staticmethod
    def _generate_html(run_id: str, markdown_text: str, base_dir: Path) -> str:
        """
        Creates a standalone HTML file with professional styling.
        """
        import base64
        import re
        
        html_path = base_dir / "FINAL_REPORT.html"
        
        # Image Replacer (Logic kept in case needed, but graphs are removed from MD upstream)
        def image_replacer(match):
            alt_text = match.group(1)
            img_filename = match.group(2)
            img_path = base_dir / img_filename
            if img_path.exists():
                with open(img_path, "rb") as img_f:
                    b64_data = base64.b64encode(img_f.read()).decode("utf-8")
                    return f'<div class="figure"><img src="data:image/png;base64,{b64_data}" alt="{alt_text}"><p class="caption">Figure: {alt_text}</p></div>'
            return f""

        # Regex
        html_content = re.sub(r'!\[(.*?)\]\((.*?)\)', image_replacer, markdown_text)
        html_content = re.sub(r'(?<!!)\[(.*?)\]\((.*?)\)', r'<a href="\2" target="_blank" class="artifact-link">\1</a>', html_content)
        
        # Structural Formatting
        html_content = html_content.replace("\n# ", "\n<h1 class='title'>").replace("</h1>\n", "</h1>")
        html_content = html_content.replace("\n## ", "\n<h2 class='section-header'>").replace("</h2>\n", "</h2>")
        html_content = html_content.replace("\n### ", "\n<h3 class='subsection-header'>").replace("</h3>\n", "</h3>")
        html_content = html_content.replace("**", "<strong>").replace("**", "</strong>")
        html_content = html_content.replace("```json", "<div class='code-block'><pre><code class='json'>").replace("```", "</code></pre></div>")
        
        # Turn bullet points into styled list items
        html_content = re.sub(r'\n- (.*)', r'\n<div class="list-item">• \1</div>', html_content)
        
        html_content = html_content.replace("\n", "<br>\n")
        
        # Cyberpunk / Sci-Fi Terminal CSS
        full_html = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>EPSILON REPORT - {run_id}</title>
            <style>
                :root {{
                    --bg-color: #0d0f14;
                    --card-bg: #13161c;
                    --text-color: #c0caf5;
                    --text-muted: #565f89;
                    --accent-color: #00ffc8;  /* Cyan Neon */
                    --accent-secondary: #7aa2f7; /* Blue Neon */
                    --border-color: #24283b;
                    --font-mono: 'JetBrains Mono', 'Fira Code', 'Consolas', monospace;
                    --glow: 0 0 10px rgba(0, 255, 200, 0.2);
                }}
                
                body {{
                    font-family: var(--font-mono);
                    background-color: var(--bg-color);
                    color: var(--text-color);
                    margin: 0;
                    padding: 40px;
                    line-height: 1.6;
                }}
                
                .container {{
                    max-width: 900px;
                    margin: 0 auto;
                    border: 1px solid var(--border-color);
                    padding: 40px;
                    background: var(--card-bg);
                    box-shadow: 0 0 30px rgba(0,0,0,0.5);
                    position: relative;
                    overflow: hidden;
                }}
                
                /* Decorative decorative top bar */
                .container::before {{
                    content: '';
                    position: absolute;
                    top: 0;
                    left: 0;
                    width: 100%;
                    height: 2px;
                    background: linear-gradient(90deg, var(--accent-color), var(--accent-secondary));
                    box-shadow: var(--glow);
                }}

                .report-header {{
                    text-align: center;
                    border-bottom: 1px dashed var(--border-color);
                    padding-bottom: 20px;
                    margin-bottom: 40px;
                }}

                .title {{
                    font-size: 2rem;
                    text-transform: uppercase;
                    letter-spacing: 2px;
                    color: var(--accent-color);
                    margin: 0;
                    text-shadow: 0 0 5px rgba(0, 255, 200, 0.4);
                }}
                
                .run-id {{
                    display: inline-block;
                    margin-top: 10px;
                    font-size: 0.8rem;
                    color: var(--text-muted);
                    border: 1px solid var(--border-color);
                    padding: 4px 10px;
                    border-radius: 4px;
                }}

                h2, .section-header {{
                    color: var(--accent-secondary);
                    font-size: 1.4rem;
                    text-transform: uppercase;
                    border-left: 3px solid var(--accent-secondary);
                    padding-left: 15px;
                    margin-top: 50px;
                    margin-bottom: 25px;
                    letter-spacing: 1px;
                }}
                
                h3, .subsection-header {{
                    color: #fff;
                    font-size: 1.1rem;
                    margin-top: 30px;
                }}

                p, li {{
                    font-size: 0.95rem;
                    color: #a9b1d6;
                }}

                .code-block {{
                    background: #0f1117;
                    border: 1px solid var(--border-color);
                    padding: 15px;
                    border-radius: 4px;
                    margin: 20px 0;
                    font-size: 0.85rem;
                    overflow-x: auto;
                    color: #e0af68; /* Orange-ish for logic */
                }}
                
                /* Styled Artifact Links as "Terminal Buttons" */
                .artifact-link {{
                    display: inline-block;
                    border: 1px solid var(--accent-color);
                    color: var(--accent-color);
                    padding: 5px 15px;
                    text-decoration: none;
                    font-size: 0.8rem;
                    text-transform: uppercase;
                    margin-right: 10px;
                    transition: all 0.2s;
                }}
                
                .artifact-link:hover {{
                    background: var(--accent-color);
                    color: #000;
                    box-shadow: var(--glow);
                }}

                .figure {{
                    border: 1px solid var(--border-color);
                    background: #000;
                    padding: 10px;
                    text-align: center;
                    margin: 30px 0;
                }}
                
                .caption {{
                    color: var(--text-muted);
                    font-size: 0.8rem;
                    margin-top: 10px;
                    font-style: italic;
                }}
                
                .list-item {{
                    margin-bottom: 8px;
                    padding-left: 10px;
                    border-left: 1px solid #24283b;
                }}

                img {{
                    max-width: 100%;
                    border: 1px solid #333;
                }}
                
                /* Scrollbar */
                ::-webkit-scrollbar {{
                    width: 8px;
                    height: 8px;
                }}
                ::-webkit-scrollbar-track {{
                    background: #0d0f14; 
                }}
                ::-webkit-scrollbar-thumb {{
                    background: #24283b; 
                }}
                ::-webkit-scrollbar-thumb:hover {{
                    background: var(--accent-secondary); 
                }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="report-header">
                    <h1 class="title">Research Log</h1>
                    <span class="run-id">ID: {run_id}</span>
                </div>
                <div class="content">
                    {html_content}
                </div>
            </div>
        </body>
        </html>
        """
        
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(full_html)
            
        return str(html_path)

    @staticmethod
    def _load_json(path: Path) -> Dict:
        if path.exists():
            try:
                return json.loads(path.read_text(encoding="utf-8"))
            except:
                return {"error": "Invalid JSON"}
        return {}

    @staticmethod
    def _generate_narrative(goal: str, dataset: Dict, results: Dict) -> Dict:
        """
        Uses direct LLM call to write sections.
        Returns dict with keys: 'executive_summary', 'methodology_description', 'results_discussion'
        """
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key or not OpenAI:
            return {
                "executive_summary": "LLM generation unavailable (Missing Key or Lib).",
                "methodology_description": "See structured data above.",
                "results_discussion": "See qualitative metrics below."
            }
            
        try:
            client = OpenAI(api_key=api_key)
            
            prompt = f"""
            You are writing a Technical Research Log for an autonomous AI engine.
            TONE: High-tech, purely analytical, concise, "Cyberpunk Scientific". Avoid fluff.
            
            GOAL: {goal}
            DATASET: {json.dumps(dataset)}
            RESULTS: {str(results)[:2000]} # Truncated to save tokens
            
            Task: Write 3 sections in JSON format.
            1. "executive_summary": High-level technical abstract of findings (approx 100 words).
            2. "methodology_description": Precise description of the algorithm/approach (approx 50 words).
            3. "results_discussion": Analytical interpretation of the metrics. Compare variance/error rates directly. (approx 150 words).
            
            Output JSON ONLY.
            """
            
            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[{"role": "user", "content": prompt}],
                response_format={"type": "json_object"}
            )
            
            content = response.choices[0].message.content
            return json.loads(content)
            
        except Exception as e:
            logger.error(f"LLM Narrative Generation Failed: {e}")
            return {
                "executive_summary": f"Generation Error: {str(e)}",
                "methodology_description": "Error",
                "results_discussion": "Error"
            }
